language: python

# use container infra for linux
sudo: false
python:
  - 3.5
install:
  - pip install cpplint

script:
  - cpplint --verbose=5 --quiet `find . -path '*' \( -name '*.h' -o -name '*.cpp' \)` -not -path "./ProjectAtum/DX9*"